### ISSUE TITLE
As I pip install the library I encountered with the following error?

### ISSUE THREAD

**Issue by erogol** [EasonLiao/CudaTree#1]
As I pip install the library I encountered with the following error?

libcurand.so.5.5: cannot open shared object file: No such file or directory

How can I solve it, any idea?

I installed pycuda by the way, it works...

**Comment by erogol** [comment]
I run following
sudo ldconfig /usr/local/cuda/lib64 

then the error is changed to 

RuntimeError: module compiled against API version 9 but this version of numpy is 7
terminate called after throwing an instance of 'std::runtime_error'
  what():  numpy failed to initialize

I guess problem is about the numpy version but do I need to update or downgrade, cannot decide.

**Comment by rjpower** [comment]
The first issue is caused because `curand` isn't distributed in the same location as the main cuda library; it looks like you've addressed that.

The second looks to be happening because you have 2 different versions of `numpy` installed. Somehow cudatree (or something it depends on) is being compiled against a newer version.  I'm not sure how this is happening; maybe @iskandr has a better idea of where the dependencies come from.

**Comment by EasonLiao** [comment]
What's the version of Numpy library you are using. I'm not totally sure if this is the problem, CudaTree uses Parakeet, it only works with the numpy of version 1.7 or higher.
